### ISSUE TITLE
Could we use `ImageLoadingOptions` when `ImagePipeline.shared.rx.loadImage`?

### ISSUE THREAD

**Issue by ostk0069** [kean/RxNuke#14]
Hi, I have a small question. ✋ 

I know that in `Nuke`, it has awesome feature called `ImageLoadingOptions`.
And my question is is it possible to use this option when I use `Nuke.ImagePipeline.shared.rx.loadImage`?
While I am reading your documentation I couldn't find any solution for this.
If there are any solutions, please tell me how.

**Comment by kean** [comment]
Hi, could you please elaborate what the use case is?

**Comment by ostk0069** [comment]
My question is simple,

Is there any way I can use transition animations when I use `Nuke.ImagePipeline.shared.rx.loadImage`?

(I know that I can solve this when `Nuke.loadImage` by using `ImageLoadingOptions` but not in rx situation)

**Comment by kean** [comment]
> Is there any way I can use transition animations when I use Nuke.ImagePipeline.shared.rx.loadImage?

Well, currently you will have to write this code yourself. `Nuke.loadImage` currently works with `ImageRequest`, I can't see how it could be generalized more to work with `RxSwift`.

**Comment by ostk0069** [comment]
Okay, Thanks for answering the question 👍
