### ISSUE TITLE
Document missing [Display Placeholder on Failure]

### ISSUE THREAD

**Issue by syq7970** [kean/RxNuke#16]
Hi:
How can I use this for show placeholder without UIImageView extension? 
like:imageURL-->ImageWithPlaceholder-->DecodedImage --> bind(to: UIImageView.rx.image) --> show with fade animation

**Comment by kean** [comment]
Hi @syq7970, this feature is not built into RxNuke. You will have to either use Nuke directly, or implement your own bind method.

**Comment by syq7970** [comment]
thx for the reply
