### ISSUE TITLE
Support RxSwift 5.1.0

### ISSUE THREAD

**Issue by 0xhiroki** [kean/RxNuke#17]
RxSwift community has recently released the version 5.1.0 which includes a fix for [Apple's hard deprecation, starting April 2020](https://developer.apple.com/news/?id=12232019b).

**Comment by kean** [comment]
RxNuke depends 'RxSwift', '~> 5.0' so it should be fine. It also doesn't depend on `RxCocoa` so I don't think there were any dependencies to `UIWebView` anyway.
