### ISSUE TITLE
UITableView sometimes shows previously queued image.

### ISSUE THREAD

**Issue by jdisho** [kean/RxNuke#4]
Hi Alexander, 

I am playing around with **Nuke**, so I created a tableview that contains cells having only an image.
While scrolling faster I realised that the **UITableView** sometimes shows previously queued image.

```
Observable.concat(nukeManager.loadImage(with: viewModel.smallPhoto).orEmpty,
                          nukeManager.loadImage(with: viewModel.regularPhoto).orEmpty)
            .bind(to: photoImageView.rx.image)
            .disposed(by: rx.disposeBag)
```

Any idea why this happens?

**Comment by kean** [comment]
Hey,

Make sure that you cancel previous subscriptions and prepare image view for reuse before loading a new image:

```swift
disposeBag = DisposeBag()
imageView.image = nil

... load image ...
```

**Comment by jdisho** [comment]
I did that, but nothing changed. 

![nuke](https://user-images.githubusercontent.com/8223362/35783455-8dd91e52-0a07-11e8-9cea-f45fa1d317b9.gif)

**Comment by kean** [comment]
> .bind(to: photoImageView.rx.image)
>            .disposed(by: rx.disposeBag)

Are you sure you're adding disposables to the correct dispose bag (the one that get's re-created)?

**Comment by jdisho** [comment]
Yes, a disposeBag is created on the cell and the same thing occurs

**Comment by jdisho** [comment]
Solved it.
