### ISSUE TITLE
Missing func loadImage(with url: URL)?

### ISSUE THREAD

**Issue by Derek-X-Wang** [kean/RxNuke#6]
The README said RxNuke has this two functions

```swift
extension ImagePipeline {
    func loadImage(with url: URL) -> Single<ImageResponse>
    func loadImage(with request: ImageRequest) -> Single<ImageResponse>
}
```

where is 
```swift
func loadImage(with url: URL) -> Single<ImageResponse>
```

Doesn't see it in the source also.

I'm using version 0.5

Just get a little bit confused by the document.

Thanks

**Comment by kean** [comment]
Hey, seems that I've forgot to actually add this variant.

**Comment by kean** [comment]
Fixed in https://github.com/kean/RxNuke/releases/tag/0.6
