### ISSUE TITLE
orEmpty operator

### ISSUE THREAD

**Issue by jdisho** [kean/RxNuke#8]
I have seen that you are using `orEmpty()` operator among some examples in the ReadMe. However,  `orEmpty()` doesn't exist in the source code. Is the ReadMe outdated or did you forget to create the operator? 😊

**Comment by kean** [comment]
RxNuke used to ship this operator but I later removed it and forgot to update the README, apparently. I think that shipping a custom operator as part of RxNuke is not the best idea - users probably already have something similar. But we should probably update the REAMDE to either use something that is built into RxSwift or add a code snippet that implements `orEmpty`.

**Comment by kean** [comment]
I opened the commit history and it seems that `orEmpty` used to be implemented like this:

```swift
extension RxSwift.PrimitiveSequence where Trait == RxSwift.SingleTrait {
    public var orEmpty: Observable<Element> {
        return self.asObservable().catchError { _ in
            return .empty()
        }
    }
}
```

So it's actually "on error complete without producing any values". I'm wondering whether this is the best we can do here. Maybe examples could be rewritten to avoid using this operator.

**Comment by jdisho** [comment]
Hi @kean 
I think is better to remove `orEmpty` operator from the ReadMe since it is a custom operator. However, I will have a better look at it today to see how we can fix it. 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kean** [comment]
Please see https://github.com/kean/RxNuke/pull/9#issuecomment-399195448
